### ISSUE TITLE
Toggle the bootstrap helper on/off

### ISSUE THREAD

**Issue by lhuiskes** [allcaps/ChromeBootstrapHelper#1]
You cant close the ChromeBootstrapHelper.
How it works now that you need to refresh the page, which is kinda frustration when you're developing and refreshing the page multiple times

**Comment by allcaps** [comment]
Yes, at the moment it only adds the indicator html to the dom a second click doesn't remove the item. Actually it adds just another indicator. Clicking multiple times will result in multiple (stacked) indicators in the dom.

**Comment by allcaps** [comment]
Fixed by c2d50ec
